title: FriezeRMQ1D
logo: /assets/img/pople5.png
description: FriezeRMQ1D Dataset for Group-Subgroup Machine Learning
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
defaults:
  layout: single
